ALTER TABLE Persons DROP FOREIGN KEY Persons_ibfk_1;

ALTER TABLE Users ADD COLUMN IDPERSONS INT NOT NULL;

ALTER TABLE Users ADD CONSTRAINT Fk_persons FOREIGN KEY (IDPERSONS) REFERENCES Persons(IDPERSONS);